# Generated by Django 5.1.1 on 2025-01-04 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_alter_publicacion_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='me_gusta',
            field=models.ManyToManyField(blank=True, related_name='me_gusta', to=settings.AUTH_USER_MODEL),
        ),
    ]
