# Generated by Django 5.1.1 on 2025-01-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0008_historia_reaccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaccion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historia',
            name='reacciones',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reaccion',
            name='tipo_reaccion',
            field=models.CharField(choices=[('me gusta', 'Me gusta'), ('no me gusta', 'No me gusta')], default='me gusta', max_length=12),
        ),
        migrations.AlterField(
            model_name='historia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reaccion',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones_usuario', to='MiApp.historia'),
        ),
        migrations.RemoveField(
            model_name='reaccion',
            name='reaccion',
        ),
    ]
