# Generated by Django 5.1.1 on 2025-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0010_remove_historia_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaccion',
            name='tipo_reaccion',
            field=models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], default='like', max_length=12),
        ),
    ]
